name: newworkflow
on: 
  workflow_dispatch:
    inputs:
      environment-name:
        type: choice
        options:
          - dev
          - qa
          - stage
          - prod
jobs:
    Build-Job:
        runs-on: ubuntu-latest
        steps:
           - name: Build Step
             run: |
               echo "Build Job executing"
    Deploy-Job:
       runs-on: ubuntu-latest
       steps:
         - name: Deploy Step
           run: |
               echo "Deploying the code to ${{ inputs.environment-name }}
               
               

  
